"""THIS IS AN AUTO-GENERATED FILE
Do not edit this file manually.
If you want to recalibrate the sensors, follow the instructions in calibrate.py.

If you are looking to use the calibration data, you should include:
from calibration_generated import *
We use * rather than calib so that we do not get an error if this file was not generated properly and we are trying to regenerate it.
"""


class _Type(object):
    __slots__ = ['x', 'y', 'z']

    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z
        
        
class _Sensor(object):
    __slots__ = ['gyro', 'accl']

    def __init__(self, gyro: _Type, accl: _Type):
        self.gyro = gyro
        self.accl = accl

        
class _Calib(object):
    __slots__ = ['tongue', 'throat']

    def __init__(self, tongue: _Sensor, throat: _Sensor):
        self.tongue = tongue
        self.throat = throat


_tongue_gyro_x = -43.2128393580321
_tongue_gyro_y = 731.4987250637469
_tongue_gyro_z = -20.226938653067347

_tongue_accl_x = 374.8474576271187
_tongue_accl_y = 1048.5036748162593
_tongue_accl_z = -32690.654942252888

_throat_gyro_x = 539.7724613769311
_throat_gyro_y = -865.3313334333284
_throat_gyro_z = -649.7562621868907

_throat_accl_x = 238.6577171141443
_throat_accl_y = 463.13199340033
_throat_accl_z = 382.97787610619343

_tongue_gyro = _Type(_tongue_gyro_x, _tongue_gyro_y, _tongue_gyro_z)
_tongue_accl = _Type(_tongue_accl_x, _tongue_accl_y, _tongue_accl_z)
_throat_gyro = _Type(_throat_gyro_x, _throat_gyro_y, _throat_gyro_z)
_throat_accl = _Type(_throat_accl_x, _throat_accl_y, _throat_accl_z)

_tongue = _Sensor(_tongue_gyro, _tongue_accl)
_throat = _Sensor(_throat_gyro, _throat_accl)

calib = _Calib(_tongue, _throat)
